// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrimeNumberService.proto

package com.primenumber.contracts;

public interface PrimeNumberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
