// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrimeNumberService.proto

package com.primenumber.contracts;

public interface PrimeNumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
