// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrimeNumberService.proto

public interface PrimeNumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
